master:
  image: redis:5
  expose:
    - 6379
slave:
  image: redis:5
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  expose:
    - 6379
sentinel:
  image: redis:5
  command: redis-server /redis-sentinel/sentinel.conf --sentinel
  volumes:
    - ./sentinel:/redis-sentinel
  links:
    - master:redis-master
    - slave
  expose:
    - 26379
